# Generated by Django 3.2.6 on 2021-08-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='students_registered',
            field=models.IntegerField(default=0),
        ),
    ]
