# Generated by Django 3.2.6 on 2021-08-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_coordinator', '0003_alter_classes_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='day',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='classes',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='classes',
            unique_together={('course_code', 'faculty', 'day', 'time')},
        ),
        migrations.RemoveField(
            model_name='classes',
            name='class_time',
        ),
    ]
