# Generated by Django 3.2.6 on 2021-08-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_coordinator', '0006_auto_20210828_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=50, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=50, default=0, max_digits=100),
        ),
    ]
